=== itdojp/white-hat-cyber-intelligence-book/schemas/site-pages.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://itdojp.github.io/white-hat-cyber-intelligence-book/schemas/site-pages.schema.json",
  "title": "Book Site Page Registry",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schemaVersion",
    "canonicalDirectories",
    "pages",
    "directoryRoutes"
  ],
  "allOf": [
    {
      "if": {
        "properties": {
          "directoryRoutes": {
            "required": [
              "cases"
            ]
          }
        }
      },
      "then": {
        "properties": {
          "canonicalDirectories": {
            "contains": {
              "const": "cases"
            }
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "directoryRoutes": {
            "required": [
              "schemas"
            ]
          }
        }
      },
      "then": {
        "properties": {
          "canonicalDirectories": {
            "contains": {
              "const": "schemas"
            }
          }
        }
      }
    }
  ],
  "properties": {
    "schemaVersion": {
      "const": "1.1.0"
    },
    "canonicalDirectories": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "cases",
          "schemas"
        ]
      }
    },
    "pages": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "source",
          "destination",
          "section",
          "order",
          "title"
        ],
        "properties": {
          "source": {
            "type": "string",
            "pattern": "^(?!/)(?!.*(?:^|/)\\.\\.(?:/|$)).+\\.md$"
          },
          "destination": {
            "type": "string",
            "pattern": "^(?!/)(?!.*(?:^|/)\\.\\.(?:/|$)).+\\.md$"
          },
          "section": {
            "enum": [
              "introduction",
              "chapters",
              "additional",
              "resources",
              "appendices",
              "afterword"
            ]
          },
          "order": {
            "type": "integer",
            "minimum": 0
          },
          "title": {
            "type": "string",
            "minLength": 1,
            "pattern": "^(?![\\uDC00-\\uDFFF])(?!.*[\\uD800-\\uDBFF](?![\\uDC00-\\uDFFF]))(?!.*[^\\uD800-\\uDBFF][\\uDC00-\\uDFFF])(?!(?:(?:[\\u0000-\\u0020\\u007F-\\u00A0\\u00AD\\u0300-\\u036F\\u0483-\\u0489\\u0591-\\u05BD\\u05BF\\u05C1-\\u05C2\\u05C4-\\u05C5\\u05C7\\u0600-\\u0605\\u0610-\\u061A\\u061C\\u064B-\\u065F\\u0670\\u06D6-\\u06DD\\u06DF-\\u06E4\\u06E7-\\u06E8\\u06EA-\\u06ED\\u070F\\u0711\\u0730-\\u074A\\u07A6-\\u07B0\\u07EB-\\u07F3\\u07FD\\u0816-\\u0819\\u081B-\\u0823\\u0825-\\u0827\\u0829-\\u082D\\u0859-\\u085B\\u0890-\\u0891\\u0898-\\u089F\\u08CA-\\u0903\\u093A-\\u093C\\u093E-\\u094F\\u0951-\\u0957\\u0962-\\u0963\\u0981-\\u0983\\u09BC\\u09BE-\\u09C4\\u09C7-\\u09C8\\u09CB-\\u09CD\\u09D7\\u09E2-\\u09E3\\u09FE\\u0A01-\\u0A03\\u0A3C\\u0A3E-\\u0A42\\u0A47-\\u0A48\\u0A4B-\\u0A4D\\u0A51\\u0A70-\\u0A71\\u0A75\\u0A81-\\u0A83\\u0ABC\\u0ABE-\\u0AC5\\u0AC7-\\u0AC9\\u0ACB-\\u0ACD\\u0AE2-\\u0AE3\\u0AFA-\\u0AFF\\u0B01-\\u0B03\\u0B3C\\u0B3E-\\u0B44\\u0B47-\\u0B48\\u0B4B-\\u0B4D\\u0B55-\\u0B57\\u0B62-\\u0B63\\u0B82\\u0BBE-\\u0BC2\\u0BC6-\\u0BC8\\u0BCA-\\u0BCD\\u0BD7\\u0C00-\\u0C04\\u0C3C\\u0C3E-\\u0C44\\u0C46-\\u0C48\\u0C4A-\\u0C4D\\u0C55-\\u0C56\\u0C62-\\u0C63\\u0C81-\\u0C83\\u0CBC\\u0CBE-\\u0CC4\\u0CC6-\\u0CC8\\u0CCA-\\u0CCD\\u0CD5-\\u0CD6\\u0CE2-\\u0CE3\\u0CF3\\u0D00-\\u0D03\\u0D3B-\\u0D3C\\u0D3E-\\u0D44\\u0D46-\\u0D48\\u0D4A-\\u0D4D\\u0D57\\u0D62-\\u0D63\\u0D81-\\u0D83\\u0DCA\\u0DCF-\\u0DD4\\u0DD6\\u0DD8-\\u0DDF\\u0DF2-\\u0DF3\\u0E31\\u0E34-\\u0E3A\\u0E47-\\u0E4E\\u0EB1\\u0EB4-\\u0EBC\\u0EC8-\\u0ECE\\u0F18-\\u0F19\\u0F35\\u0F37\\u0F39\\u0F3E-\\u0F3F\\u0F71-\\u0F84\\u0F86-\\u0F87\\u0F8D-\\u0F97\\u0F99-\\u0FBC\\u0FC6\\u102B-\\u103E\\u1056-\\u1059\\u105E-\\u1060\\u1062-\\u1064\\u1067-\\u106D\\u1071-\\u1074\\u1082-\\u108D\\u108F\\u109A-\\u109D\\u115F\\u135D-\\u135F\\u1680\\u1712-\\u1715\\u1732-\\u1734\\u1752-\\u1753\\u1772-\\u1773\\u17B4-\\u17D3\\u17DD\\u180B-\\u180F\\u1885-\\u1886\\u18A9\\u1920-\\u192B\\u1930-\\u193B\\u1A17-\\u1A1B\\u1A55-\\u1A5E\\u1A60-\\u1A7C\\u1A7F\\u1AB0-\\u1ACE\\u1B00-\\u1B04\\u1B34-\\u1B44\\u1B6B-\\u1B73\\u1B80-\\u1B82\\u1BA1-\\u1BAD\\u1BE6-\\u1BF3\\u1C24-\\u1C37\\u1CD0-\\u1CD2\\u1CD4-\\u1CE8\\u1CED\\u1CF4\\u1CF7-\\u1CF9\\u1DC0-\\u1DFF\\u2000-\\u200F\\u2028-\\u202F\\u205F-\\u2064\\u2066-\\u206F\\u20D0-\\u20F0\\u2800\\u2CEF-\\u2CF1\\u2D7F\\u2DE0-\\u2DFF\\u3000\\u302A-\\u302F\\u3099-\\u309A\\u3164\\uA66F-\\uA672\\uA674-\\uA67D\\uA69E-\\uA69F\\uA6F0-\\uA6F1\\uA802\\uA806\\uA80B\\uA823-\\uA827\\uA82C\\uA880-\\uA881\\uA8B4-\\uA8C5\\uA8E0-\\uA8F1\\uA8FF\\uA926-\\uA92D\\uA947-\\uA953\\uA980-\\uA983\\uA9B3-\\uA9C0\\uA9E5\\uAA29-\\uAA36\\uAA43\\uAA4C-\\uAA4D\\uAA7B-\\uAA7D\\uAAB0\\uAAB2-\\uAAB4\\uAAB7-\\uAAB8\\uAABE-\\uAABF\\uAAC1\\uAAEB-\\uAAEF\\uAAF5-\\uAAF6\\uABE3-\\uABEA\\uABEC-\\uABED\\uFB1E\\uFE00-\\uFE0F\\uFE20-\\uFE2F\\uFEFF\\uFFA0\\uFFF9-\\uFFFB]|(?:𐇽|𐋠|𐍶|𐍷|𐍸|𐍹|𐍺|𐨁|𐨂|𐨃|𐨅|𐨆|𐨌|𐨍|𐨎|𐨏|𐨸|𐨹|𐨺|𐨿|𐫥|𐫦|𐴤|𐴥|𐴦|𐴧|𐺫|𐺬|𐻽|𐻾|𐻿|𐽆|𐽇|𐽈|𐽉|𐽊|𐽋|𐽌|𐽍|𐽎|𐽏|𐽐|𐾂|𐾃|𐾄|𐾅|𑀀|𑀁|𑀂|𑀸|𑀹|𑀺|𑀻|𑀼|𑀽|𑀾|𑀿|𑁀|𑁁|𑁂|𑁃|𑁄|𑁅|𑁆|𑁰|𑁳|𑁴|𑁿|𑂀|𑂁|𑂂|𑂰|𑂱|𑂲|𑂳|𑂴|𑂵|𑂶|𑂷|𑂸|𑂹|𑂺|𑂽|𑃂|𑃍|𑄀|𑄁|𑄂|𑄧|𑄨|𑄩|𑄪|𑄫|𑄬|𑄭|𑄮|𑄯|𑄰|𑄱|𑄲|𑄳|𑄴|𑅅|𑅆|𑅳|𑆀|𑆁|𑆂|𑆳|𑆴|𑆵|𑆶|𑆷|𑆸|𑆹|𑆺|𑆻|𑆼|𑆽|𑆾|𑆿|𑇀|𑇉|𑇊|𑇋|𑇌|𑇎|𑇏|𑈬|𑈭|𑈮|𑈯|𑈰|𑈱|𑈲|𑈳|𑈴|𑈵|𑈶|𑈷|𑈾|𑉁|𑋟|𑋠|𑋡|𑋢|𑋣|𑋤|𑋥|𑋦|𑋧|𑋨|𑋩|𑋪|𑌀|𑌁|𑌂|𑌃|𑌻|𑌼|𑌾|𑌿|𑍀|𑍁|𑍂|𑍃|𑍄|𑍇|𑍈|𑍋|𑍌|𑍍|𑍗|𑍢|𑍣|𑍦|𑍧|𑍨|𑍩|𑍪|𑍫|𑍬|𑍰|𑍱|𑍲|𑍳|𑍴|𑐵|𑐶|𑐷|𑐸|𑐹|𑐺|𑐻|𑐼|𑐽|𑐾|𑐿|𑑀|𑑁|𑑂|𑑃|𑑄|𑑅|𑑆|𑑞|𑒰|𑒱|𑒲|𑒳|𑒴|𑒵|𑒶|𑒷|𑒸|𑒹|𑒺|𑒻|𑒼|𑒽|𑒾|𑒿|𑓀|𑓁|𑓂|𑓃|𑖯|𑖰|𑖱|𑖲|𑖳|𑖴|𑖵|𑖸|𑖹|𑖺|𑖻|𑖼|𑖽|𑖾|𑖿|𑗀|𑗜|𑗝|𑘰|𑘱|𑘲|𑘳|𑘴|𑘵|𑘶|𑘷|𑘸|𑘹|𑘺|𑘻|𑘼|𑘽|𑘾|𑘿|𑙀|𑚫|𑚬|𑚭|𑚮|𑚯|𑚰|𑚱|𑚲|𑚳|𑚴|𑚵|𑚶|𑚷|𑜝|𑜞|𑜟|𑜠|𑜡|𑜢|𑜣|𑜤|𑜥|𑜦|𑜧|𑜨|𑜩|𑜪|𑜫|𑠬|𑠭|𑠮|𑠯|𑠰|𑠱|𑠲|𑠳|𑠴|𑠵|𑠶|𑠷|𑠸|𑠹|𑠺|𑤰|𑤱|𑤲|𑤳|𑤴|𑤵|𑤷|𑤸|𑤻|𑤼|𑤽|𑤾|𑥀|𑥂|𑥃|𑧑|𑧒|𑧓|𑧔|𑧕|𑧖|𑧗|𑧚|𑧛|𑧜|𑧝|𑧞|𑧟|𑧠|𑧤|𑨁|𑨂|𑨃|𑨄|𑨅|𑨆|𑨇|𑨈|𑨉|𑨊|𑨳|𑨴|𑨵|𑨶|𑨷|𑨸|𑨹|𑨻|𑨼|𑨽|𑨾|𑩇|𑩑|𑩒|𑩓|𑩔|𑩕|𑩖|𑩗|𑩘|𑩙|𑩚|𑩛|𑪊|𑪋|𑪌|𑪍|𑪎|𑪏|𑪐|𑪑|𑪒|𑪓|𑪔|𑪕|𑪖|𑪗|𑪘|𑪙|𑰯|𑰰|𑰱|𑰲|𑰳|𑰴|𑰵|𑰶|𑰸|𑰹|𑰺|𑰻|𑰼|𑰽|𑰾|𑰿|𑲒|𑲓|𑲔|𑲕|𑲖|𑲗|𑲘|𑲙|𑲚|𑲛|𑲜|𑲝|𑲞|𑲟|𑲠|𑲡|𑲢|𑲣|𑲤|𑲥|𑲦|𑲧|𑲩|𑲪|𑲫|𑲬|𑲭|𑲮|𑲯|𑲰|𑲱|𑲲|𑲳|𑲴|𑲵|𑲶|𑴱|𑴲|𑴳|𑴴|𑴵|𑴶|𑴺|𑴼|𑴽|𑴿|𑵀|𑵁|𑵂|𑵃|𑵄|𑵅|𑵇|𑶊|𑶋|𑶌|𑶍|𑶎|𑶐|𑶑|𑶓|𑶔|𑶕|𑶖|𑶗|𑻳|𑻴|𑻵|𑻶|𑼀|𑼁|𑼃|𑼴|𑼵|𑼶|𑼷|𑼸|𑼹|𑼺|𑼾|𑼿|𑽀|𑽁|𑽂|𓐰|𓐱|𓐲|𓐳|𓐴|𓐵|𓐶|𓐷|𓐸|𓐹|𓐺|𓐻|𓐼|𓐽|𓐾|𓐿|𓑀|𓑇|𓑈|𓑉|𓑊|𓑋|𓑌|𓑍|𓑎|𓑏|𓑐|𓑑|𓑒|𓑓|𓑔|𓑕|𖫰|𖫱|𖫲|𖫳|𖫴|𖬰|𖬱|𖬲|𖬳|𖬴|𖬵|𖬶|𖽏|𖽑|𖽒|𖽓|𖽔|𖽕|𖽖|𖽗|𖽘|𖽙|𖽚|𖽛|𖽜|𖽝|𖽞|𖽟|𖽠|𖽡|𖽢|𖽣|𖽤|𖽥|𖽦|𖽧|𖽨|𖽩|𖽪|𖽫|𖽬|𖽭|𖽮|𖽯|𖽰|𖽱|𖽲|𖽳|𖽴|𖽵|𖽶|𖽷|𖽸|𖽹|𖽺|𖽻|𖽼|𖽽|𖽾|𖽿|𖾀|𖾁|𖾂|𖾃|𖾄|𖾅|𖾆|𖾇|𖾏|𖾐|𖾑|𖾒|𖿤|𖿰|𖿱|𛲝|𛲞|𛲠|𛲡|𛲢|𛲣|𜼀|𜼁|𜼂|𜼃|𜼄|𜼅|𜼆|𜼇|𜼈|𜼉|𜼊|𜼋|𜼌|𜼍|𜼎|𜼏|𜼐|𜼑|𜼒|𜼓|𜼔|𜼕|𜼖|𜼗|𜼘|𜼙|𜼚|𜼛|𜼜|𜼝|𜼞|𜼟|𜼠|𜼡|𜼢|𜼣|𜼤|𜼥|𜼦|𜼧|𜼨|𜼩|𜼪|𜼫|𜼬|𜼭|𜼰|𜼱|𜼲|𜼳|𜼴|𜼵|𜼶|𜼷|𜼸|𜼹|𜼺|𜼻|𜼼|𜼽|𜼾|𜼿|𜽀|𜽁|𜽂|𜽃|𜽄|𜽅|𜽆|𝅥|𝅦|𝅧|𝅨|𝅩|𝅭|𝅮|𝅯|𝅰|𝅱|𝅲|𝅳|𝅴|𝅵|𝅶|𝅷|𝅸|𝅹|𝅺|𝅻|𝅼|𝅽|𝅾|𝅿|𝆀|𝆁|𝆂|𝆅|𝆆|𝆇|𝆈|𝆉|𝆊|𝆋|𝆪|𝆫|𝆬|𝆭|𝉂|𝉃|𝉄|𝨀|𝨁|𝨂|𝨃|𝨄|𝨅|𝨆|𝨇|𝨈|𝨉|𝨊|𝨋|𝨌|𝨍|𝨎|𝨏|𝨐|𝨑|𝨒|𝨓|𝨔|𝨕|𝨖|𝨗|𝨘|𝨙|𝨚|𝨛|𝨜|𝨝|𝨞|𝨟|𝨠|𝨡|𝨢|𝨣|𝨤|𝨥|𝨦|𝨧|𝨨|𝨩|𝨪|𝨫|𝨬|𝨭|𝨮|𝨯|𝨰|𝨱|𝨲|𝨳|𝨴|𝨵|𝨶|𝨻|𝨼|𝨽|𝨾|𝨿|𝩀|𝩁|𝩂|𝩃|𝩄|𝩅|𝩆|𝩇|𝩈|𝩉|𝩊|𝩋|𝩌|𝩍|𝩎|𝩏|𝩐|𝩑|𝩒|𝩓|𝩔|𝩕|𝩖|𝩗|𝩘|𝩙|𝩚|𝩛|𝩜|𝩝|𝩞|𝩟|𝩠|𝩡|𝩢|𝩣|𝩤|𝩥|𝩦|𝩧|𝩨|𝩩|𝩪|𝩫|𝩬|𝩵|𝪄|𝪛|𝪜|𝪝|𝪞|𝪟|𝪡|𝪢|𝪣|𝪤|𝪥|𝪦|𝪧|𝪨|𝪩|𝪪|𝪫|𝪬|𝪭|𝪮|𝪯|𞀀|𞀁|𞀂|𞀃|𞀄|𞀅|𞀆|𞀈|𞀉|𞀊|𞀋|𞀌|𞀍|𞀎|𞀏|𞀐|𞀑|𞀒|𞀓|𞀔|𞀕|𞀖|𞀗|𞀘|𞀛|𞀜|𞀝|𞀞|𞀟|𞀠|𞀡|𞀣|𞀤|𞀦|𞀧|𞀨|𞀩|𞀪|𞂏|𞄰|𞄱|𞄲|𞄳|𞄴|𞄵|𞄶|𞊮|𞋬|𞋭|𞋮|𞋯|𞓬|𞓭|𞓮|𞓯|𞣐|𞣑|𞣒|𞣓|𞣔|𞣕|𞣖|𞥄|𞥅|𞥆|𞥇|𞥈|𞥉|𞥊|󠀁|󠀠|󠀡|󠀢|󠀣|󠀤|󠀥|󠀦|󠀧|󠀨|󠀩|󠀪|󠀫|󠀬|󠀭|󠀮|󠀯|󠀰|󠀱|󠀲|󠀳|󠀴|󠀵|󠀶|󠀷|󠀸|󠀹|󠀺|󠀻|󠀼|󠀽|󠀾|󠀿|󠁀|󠁁|󠁂|󠁃|󠁄|󠁅|󠁆|󠁇|󠁈|󠁉|󠁊|󠁋|󠁌|󠁍|󠁎|󠁏|󠁐|󠁑|󠁒|󠁓|󠁔|󠁕|󠁖|󠁗|󠁘|󠁙|󠁚|󠁛|󠁜|󠁝|󠁞|󠁟|󠁠|󠁡|󠁢|󠁣|󠁤|󠁥|󠁦|󠁧|󠁨|󠁩|󠁪|󠁫|󠁬|󠁭|󠁮|󠁯|󠁰|󠁱|󠁲|󠁳|󠁴|󠁵|󠁶|󠁷|󠁸|󠁹|󠁺|󠁻|󠁼|󠁽|󠁾|󠁿|󠄀|󠄁|󠄂|󠄃|󠄄|󠄅|󠄆|󠄇|󠄈|󠄉|󠄊|󠄋|󠄌|󠄍|󠄎|󠄏|󠄐|󠄑|󠄒|󠄓|󠄔|󠄕|󠄖|󠄗|󠄘|󠄙|󠄚|󠄛|󠄜|󠄝|󠄞|󠄟|󠄠|󠄡|󠄢|󠄣|󠄤|󠄥|󠄦|󠄧|󠄨|󠄩|󠄪|󠄫|󠄬|󠄭|󠄮|󠄯|󠄰|󠄱|󠄲|󠄳|󠄴|󠄵|󠄶|󠄷|󠄸|󠄹|󠄺|󠄻|󠄼|󠄽|󠄾|󠄿|󠅀|󠅁|󠅂|󠅃|󠅄|󠅅|󠅆|󠅇|󠅈|󠅉|󠅊|󠅋|󠅌|󠅍|󠅎|󠅏|󠅐|󠅑|󠅒|󠅓|󠅔|󠅕|󠅖|󠅗|󠅘|󠅙|󠅚|󠅛|󠅜|󠅝|󠅞|󠅟|󠅠|󠅡|󠅢|󠅣|󠅤|󠅥|󠅦|󠅧|󠅨|󠅩|󠅪|󠅫|󠅬|󠅭|󠅮|󠅯|󠅰|󠅱|󠅲|󠅳|󠅴|󠅵|󠅶|󠅷|󠅸|󠅹|󠅺|󠅻|󠅼|󠅽|󠅾|󠅿|󠆀|󠆁|󠆂|󠆃|󠆄|󠆅|󠆆|󠆇|󠆈|󠆉|󠆊|󠆋|󠆌|󠆍|󠆎|󠆏|󠆐|󠆑|󠆒|󠆓|󠆔|󠆕|󠆖|󠆗|󠆘|󠆙|󠆚|󠆛|󠆜|󠆝|󠆞|󠆟|󠆠|󠆡|󠆢|󠆣|󠆤|󠆥|󠆦|󠆧|󠆨|󠆩|󠆪|󠆫|󠆬|󠆭|󠆮|󠆯|󠆰|󠆱|󠆲|󠆳|󠆴|󠆵|󠆶|󠆷|󠆸|󠆹|󠆺|󠆻|󠆼|󠆽|󠆾|󠆿|󠇀|󠇁|󠇂|󠇃|󠇄|󠇅|󠇆|󠇇|󠇈|󠇉|󠇊|󠇋|󠇌|󠇍|󠇎|󠇏|󠇐|󠇑|󠇒|󠇓|󠇔|󠇕|󠇖|󠇗|󠇘|󠇙|󠇚|󠇛|󠇜|󠇝|󠇞|󠇟|󠇠|󠇡|󠇢|󠇣|󠇤|󠇥|󠇦|󠇧|󠇨|󠇩|󠇪|󠇫|󠇬|󠇭|󠇮|󠇯)))+$)[^\\u0000-\\u001F\\u007F-\\u009F<>\\r\\n\\u2028\\u2029]+$"
          }
        }
      }
    },
    "directoryRoutes": {
      "type": "object",
      "propertyNames": {
        "enum": [
          "cases",
          "schemas"
        ]
      },
      "additionalProperties": {
        "type": "string",
        "pattern": "^(?!/)(?!.*(?:^|/)\\.\\.(?:/|$)).+\\.md$"
      }
    },
    "staticFiles": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "source",
          "destination"
        ],
        "properties": {
          "source": {
            "type": "string",
            "pattern": "^(?!/)(?!.*//)(?!.*(?:^|/)\\.\\.(?:/|$))(?!.*(?:^|/)[._])[A-Za-z0-9][A-Za-z0-9._/-]*\\.json$"
          },
          "destination": {
            "type": "string",
            "pattern": "^downloads/(?![._])(?!.*//)(?!.*\/[._])[A-Za-z0-9][A-Za-z0-9._/-]*\\.json$"
          }
        }
      }
    }
  }
}

=== itdojp/white-hat-cyber-intelligence-book/site-pages.json
{
  "schemaVersion": "1.1.0",
  "canonicalDirectories": [
    "cases",
    "schemas"
  ],
  "pages": [
    {
      "source": "manuscript/02-law-ethics-authorization.md",
      "destination": "chapters/chapter-02/index.md",
      "section": "chapters",
      "order": 45,
      "title": "第2章 法、倫理、許可、責任ある開示"
    },
    {
      "source": "manuscript/03-capability-evidence.md",
      "destination": "chapters/chapter-03/index.md",
      "section": "chapters",
      "order": 46,
      "title": "第3章 能力を分解し、証拠で学習する"
    },
    {
      "source": "manuscript/04-assets-boundaries-threat-model.md",
      "destination": "chapters/chapter-04/index.md",
      "section": "chapters",
      "order": 47,
      "title": "第4章 資産、信頼境界、攻撃面、脅威モデル"
    },
    {
      "source": "manuscript/11-web-api-hypothesis.md",
      "destination": "chapters/chapter-11/index.md",
      "section": "chapters",
      "order": 54,
      "title": "第11章 Web・APIを仮説駆動で評価する"
    },
    {
      "source": "templates/integrated-security-case-map.md",
      "destination": "templates/integrated-security-case-map/index.md",
      "section": "additional",
      "order": 220,
      "title": "Integrated Security Case Map"
    },
    {
      "source": "cases/ch01-integrated-security-case-example.md",
      "destination": "cases/chapter-01-integrated-security-case/index.md",
      "section": "additional",
      "order": 230,
      "title": "第1章 合成記入例：請求書連携OAuthアプリの権限見直し"
    },
    {
      "source": "templates/authorization-checklist.md",
      "destination": "templates/authorization-checklist/index.md",
      "section": "additional",
      "order": 232,
      "title": "Authorization Checklist"
    },
    {
      "source": "cases/ch02-authorization-decision-example.md",
      "destination": "cases/chapter-02-authorization-decision/index.md",
      "section": "additional",
      "order": 233,
      "title": "第2章 合成記入例：OAuth連携評価前のAuthorization判断"
    },
    {
      "source": "templates/capability-evidence-matrix.md",
      "destination": "templates/capability-evidence-matrix/index.md",
      "section": "additional",
      "order": 234,
      "title": "Capability Evidence Matrix"
    },
    {
      "source": "cases/ch03-capability-evidence-example.md",
      "destination": "cases/chapter-03-capability-evidence/index.md",
      "section": "additional",
      "order": 236,
      "title": "第3章 合成記入例：Capability Evidence Matrix"
    },
    {
      "source": "references/ch03-source-review-2026-08-05.md",
      "destination": "references/chapter-03-source-review/index.md",
      "section": "additional",
      "order": 237,
      "title": "第3章 Source Review Note：NICE Framework"
    },
    {
      "source": "cases/index.md",
      "destination": "cases/index.md",
      "section": "additional",
      "order": 238,
      "title": "合成Case索引"
    },
    {
      "source": "templates/web-api-assessment-hypothesis-pack.md",
      "destination": "templates/web-api-assessment-hypothesis-pack/index.md",
      "section": "additional",
      "order": 240,
      "title": "Web/API Assessment Hypothesis Pack"
    },
    {
      "source": "templates/threat-model.md",
      "destination": "templates/threat-model/index.md",
      "section": "additional",
      "order": 150,
      "title": "Threat Model"
    },
    {
      "source": "cases/ch04-threat-model-example.md",
      "destination": "cases/chapter-04-threat-model/index.md",
      "section": "additional",
      "order": 241,
      "title": "第4章 合成記入例：資産・信頼境界・脅威モデル"
    },
    {
      "source": "references/ch04-source-review-2026-08-08.md",
      "destination": "references/chapter-04-source-review/index.md",
      "section": "additional",
      "order": 242,
      "title": "第4章 Source Review Note：Threat Model"
    },
    {
      "source": "cases/ch11-web-api-assessment-example.md",
      "destination": "cases/chapter-11-web-api-assessment/index.md",
      "section": "additional",
      "order": 250,
      "title": "第11章 合成記入例：マルチテナント受注Export APIとWebhook登録の評価"
    },
    {
      "source": "manuscript/17-detection-engineering.md",
      "destination": "chapters/chapter-17/index.md",
      "section": "chapters",
      "order": 200,
      "title": "第17章 Detection Engineering"
    },
    {
      "source": "cases/ch17-detection-validation-example.md",
      "destination": "cases/chapter-17-detection-validation/index.md",
      "section": "additional",
      "order": 260,
      "title": "第17章 合成記入例：未承認管理者同意変更のDetection Validation"
    },
    {
      "source": "cases/fixtures/ch17-detection-engineering-fixture.md",
      "destination": "cases/fixtures/ch17-detection-engineering-fixture/index.md",
      "section": "additional",
      "order": 270,
      "title": "第17章 オフラインfixture：未承認管理者同意変更の検知検証"
    },
    {
      "source": "templates/analytic-judgment-record.md",
      "destination": "templates/analytic-judgment-record/index.md",
      "section": "additional",
      "order": 280,
      "title": "Analytic Judgment Record"
    },
    {
      "source": "cases/fixtures/index.md",
      "destination": "cases/fixtures/index.md",
      "section": "additional",
      "order": 290,
      "title": "Fixture Catalog"
    },
    {
      "source": "cases/ch25-structured-analysis-attribution-example.md",
      "destination": "cases/chapter-25-structured-analysis-attribution/index.md",
      "section": "additional",
      "order": 300,
      "title": "第25章 合成記入例：共同報告に埋もれた技術クラスタの判断"
    },
    {
      "source": "manuscript/25-structured-analysis-attribution.md",
      "destination": "chapters/chapter-25/index.md",
      "section": "chapters",
      "order": 210,
      "title": "第25章 構造化分析、不確実性、アトリビューション"
    },
    {
      "source": "manuscript/05-attack-behavior.md",
      "destination": "chapters/chapter-05/index.md",
      "section": "chapters",
      "order": 48,
      "title": "第5章 攻撃者の行動をATT&CKで記述する"
    },
    {
      "source": "templates/attack-behavior-map.md",
      "destination": "templates/attack-behavior-map/index.md",
      "section": "additional",
      "order": 243,
      "title": "ATT&CK Behavior Map"
    },
    {
      "source": "cases/ch05-attack-behavior-example.md",
      "destination": "cases/chapter-05-attack-behavior/index.md",
      "section": "additional",
      "order": 244,
      "title": "第5章 合成記入例：ATT&CK Behavior Map"
    },
    {
      "source": "references/ch05-source-review-2026-09-06.md",
      "destination": "references/chapter-05-source-review/index.md",
      "section": "additional",
      "order": 245,
      "title": "第5章 Source Review Note：ATT&CK"
    },
    {
      "source": "manuscript/06-observable-systems.md",
      "destination": "chapters/chapter-06/index.md",
      "section": "chapters",
      "order": 49,
      "title": "第6章 通信・Identity・Cloudを観測可能なシステムとして読む"
    },
    {
      "source": "templates/signal-flow-diagram.md",
      "destination": "templates/signal-flow-diagram/index.md",
      "section": "additional",
      "order": 246,
      "title": "Signal Flow Diagram"
    },
    {
      "source": "cases/ch06-signal-flow-example.md",
      "destination": "cases/chapter-06-signal-flow/index.md",
      "section": "additional",
      "order": 247,
      "title": "第6章 完全合成記入例：Signal Flow Diagram"
    },
    {
      "source": "references/ch06-source-review-2026-09-12.md",
      "destination": "references/chapter-06-source-review/index.md",
      "section": "additional",
      "order": 248,
      "title": "第6章 Source Review Note：Signal Flow"
    },
    {
      "source": "manuscript/07-vulnerability-prioritization.md",
      "destination": "chapters/chapter-07/index.md",
      "section": "chapters",
      "order": 50,
      "title": "第7章 脆弱性、露出、悪用可能性、事業影響を分ける"
    },
    {
      "source": "templates/vulnerability-prioritization-record.md",
      "destination": "templates/vulnerability-prioritization-record/index.md",
      "section": "additional",
      "order": 251,
      "title": "Vulnerability Prioritization Record"
    },
    {
      "source": "cases/ch07-vulnerability-prioritization-example.md",
      "destination": "cases/chapter-07-vulnerability-prioritization/index.md",
      "section": "additional",
      "order": 252,
      "title": "第7章 完全合成記入例：Vulnerability Prioritization Record"
    },
    {
      "source": "references/ch07-source-review-2026-09-12.md",
      "destination": "references/chapter-07-source-review/index.md",
      "section": "additional",
      "order": 253,
      "title": "第7章 Source Review Note：Vulnerability Prioritization"
    },
    {
      "source": "manuscript/08-safe-lab-evidence.md",
      "destination": "chapters/chapter-08/index.md",
      "section": "chapters",
      "order": 51,
      "title": "第8章 安全で再現可能なラボと証拠管理"
    },
    {
      "source": "templates/lab-safety-evidence-plan.md",
      "destination": "templates/lab-safety-evidence-plan/index.md",
      "section": "additional",
      "order": 254,
      "title": "Lab Safety and Evidence Plan"
    },
    {
      "source": "cases/ch08-lab-evidence-example.md",
      "destination": "cases/chapter-08-lab-evidence/index.md",
      "section": "additional",
      "order": 255,
      "title": "第8章 完全合成記入例：Lab Safety and Evidence Plan"
    },
    {
      "source": "references/ch08-source-review-2026-09-13.md",
      "destination": "references/chapter-08-source-review/index.md",
      "section": "additional",
      "order": 256,
      "title": "第8章 Source Review Note：Lab SafetyとEvidence"
    },
    {
      "source": "manuscript/09-engagement-roe.md",
      "destination": "chapters/chapter-09/index.md",
      "section": "chapters",
      "order": 52,
      "title": "第9章 Engagement DesignとRules of Engagement"
    },
    {
      "source": "cases/ch09-engagement-roe-example.md",
      "destination": "cases/chapter-09-engagement-roe/index.md",
      "section": "additional",
      "order": 257,
      "title": "第9章 完全合成記入例：Rules of Engagement"
    },
    {
      "source": "references/ch09-source-review-2026-09-13.md",
